//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_MasterDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingEntry
    {
        public int BookingEntryId { get; set; }
        public int ClientId { get; set; }
        public int SpotId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Spot Spot { get; set; }
    }
}
